[package]
name = "auto-pagefind"
description = "Pagefind for servers. Great for next.js non output export applications. Fully crawl and index your app in one command."
version = "0.1.4"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
