[package]
name = "next-pagefind"
description = "Pagefind for next.js non output export applications. Fully crawl and index your app in one command."
version = "0.1.3"
edition = "2021"
license = "MIT"

[dependencies]
